// Structural import-order gate: capture controller primitives before any loader below can import
// generated source, including direct contracts.ts callers that do not enter through falsify.ts.
import { join, relative } from "../meta/path.ts";
import { sha256 } from "../meta/digest.ts";
import { controllerValidatedFindings, type ContractFinding } from "./brief.ts";
import * as ts from "typescript5";
import { EVALUATOR_FILE, GENERATED_TOOLS_FILE } from "../meta/bundle-layout.ts";

/**
 * falsifier-claude-004: the Correctness Model evaluator called `relationalJoin(left, right, spec)` against
 * the primitive's one-spec-object signature, so `spec.left` was undefined and every evaluate() call
 * failed with "entities is not iterable", recorded as a runtime non-result. Types are erased at
 * load, so incorrect API calls can pass text checks and the load probe. This compiles the
 * generated module (noEmit) against the real package types and returns compile errors as
 * repairable findings naming the exact call site. `strict` stays off because the probe
 * enforces API contracts (arity, argument shape, member existence — none of which are
 * strict-gated), not annotation style; noImplicitAny over any-first generated code would spend
 * repair rounds on annotations without establishing additional correctness.
 */
const PROBE_COMPILER_OPTIONS: ts.CompilerOptions = {
  noEmit: true,
  strict: false,
  // ES2025, which Bun 1.4.2 runs. TypeScript 5.9 has no es2025 lib, so name its parts: Set
  // methods, iterator helpers, Promise.try and Float16Array. Target ES2024 already admits the
  // ES2025 regex syntax (modifiers, duplicate named groups).
  target: ts.ScriptTarget.ES2024,
  lib: [
    "lib.es2024.d.ts",
    "lib.esnext.collection.d.ts",
    "lib.esnext.iterator.d.ts",
    "lib.esnext.promise.d.ts",
    "lib.esnext.float16.d.ts",
  ],
  // Bundler resolution, not NodeNext: the vendored bundle packages (correctness-model-prims, agent-bundle,
  // …) use extensionless relative imports per their own tsconfigs, while the rest of the repo
  // uses .ts extensions — Bundler accepts both, NodeNext silently empties the vendored packages'
  // re-exports and misreports real primitives as missing members.
  module: ts.ModuleKind.ESNext,
  moduleResolution: ts.ModuleResolutionKind.Bundler,
  allowImportingTsExtensions: true,
  // Generated modules run under Bun, and the starter's own tests read files through `Bun.file`;
  // run 8729bb was refused for `Bun.write` in a reference with advice to install types it cannot.
  types: ["bun"],
  typeRoots: [join(new URL("../../node_modules/@types", import.meta.url).pathname)],
  skipLibCheck: true,
};

/**
 * One shared parsed-SourceFile cache across probe programs. A cold ts.createProgram re-parses the
 * language libs and vendored-package typings on every call, which dominated the control probe's
 * wall time (~2-3s per program, measured 2026-08-21). Files inside the generated slug tree are
 * never cached: they are exactly the bytes an authoring attempt rewrites, so they always parse
 * fresh. Everything else (libs, vendored typings) is process-stable; the cache key carries size
 * and mtime so an edited dependency invalidates its own entry instead of serving stale syntax.
 */
const probeSourceCache = new Map<string, ts.SourceFile>();

/**
 * One answer the compiler host gave about a path inside the generated tree, keyed by the path
 * relative to that tree. A verdict is a function of these answers and of the process-stable
 * typings outside the tree, so a tree whose answers all repeat gets the cached verdict
 * without a new checker: warm, the agent toolset program alone cost 1.7 s of type instantiation
 * per gate (measured 2026-09-13), and a gate over unchanged generated bytes is the common case.
 */
interface Probe {
  kind: "exists" | "dir" | "read" | "real" | "stable";
  path: string;
  answer: string;
}
interface CachedVerdict {
  probes: Probe[];
  findings: ContractFinding[];
}
const VERDICTS_BY_BUNDLE = new Map<string, CachedVerdict[]>();
const CACHED_VERDICTS = 8;

const flag = (value: boolean) => (value ? "1" : "0");
const readAnswer = (text: string | undefined) => (text === undefined ? "-" : sha256(text));
const realAnswer = (real: string, root: string) => (real.startsWith(root) ? real.slice(root.length) : real);
const stableAnswer = (path: string) => `${Bun.file(path).size}@${Bun.file(path).lastModified}`;
const slash = (path: string) => path.replace(/\\/g, "/");

function createProbeCompilerHost(slugDir: string, probes: Map<string, Probe>): ts.CompilerHost {
  const host = ts.createCompilerHost(PROBE_COMPILER_OPTIONS);
  const root = `${slash(slugDir)}/`;
  const base = {
    getSourceFile: host.getSourceFile.bind(host),
    fileExists: host.fileExists.bind(host),
    readFile: host.readFile.bind(host),
    directoryExists: host.directoryExists?.bind(host),
    realpath: host.realpath?.bind(host),
  };
  const note = (kind: Probe["kind"], name: string, answer: string) => {
    const path = slash(name);
    if (path.startsWith(root)) {
      probes.set(`${kind}\0${path.slice(root.length)}`, { kind, path: path.slice(root.length), answer });
    }
  };
  host.fileExists = (name) => {
    const found = base.fileExists(name);
    note("exists", name, flag(found));
    return found;
  };
  host.directoryExists = (name) => {
    const found = base.directoryExists?.(name) ?? false;
    note("dir", name, flag(found));
    return found;
  };
  host.readFile = (name) => {
    const text = base.readFile(name);
    note("read", name, readAnswer(text));
    return text;
  };
  if (base.realpath !== undefined) {
    const { realpath } = base;
    host.realpath = (name) => {
      const real = realpath(name);
      note("real", name, realAnswer(slash(real), root));
      return real;
    };
  }
  host.getSourceFile = (fileName, languageVersionOrOptions, onError, shouldCreate) => {
    if (shouldCreate === true) {
      return base.getSourceFile(fileName, languageVersionOrOptions, onError, shouldCreate);
    }
    const path = slash(fileName);
    // Generated files are read through host.readFile above, which records their bytes.
    if (path.startsWith(root) && !path.includes("/node_modules/")) {
      return base.getSourceFile(fileName, languageVersionOrOptions, onError);
    }
    note("stable", fileName, stableAnswer(fileName));
    const key = `${path}@${stableAnswer(fileName)}`;
    const cached = probeSourceCache.get(key);
    if (cached !== undefined) return cached;
    const sourceFile = base.getSourceFile(fileName, languageVersionOrOptions, onError);
    if (sourceFile !== undefined) {
      if (probeSourceCache.size >= 5_000) probeSourceCache.clear();
      probeSourceCache.set(key, sourceFile);
    }
    return sourceFile;
  };
  return host;
}

/** The answer the filesystem gives today for one cached probe of another (or the same) tree. */
function currentAnswer(host: ts.CompilerHost, root: string, probe: Probe): string {
  const path = root + probe.path;
  switch (probe.kind) {
    case "exists":
      return flag(host.fileExists(path));
    case "dir":
      return flag(host.directoryExists?.(path) ?? false);
    case "read":
      return readAnswer(host.readFile(path));
    case "real":
      return realAnswer(slash(host.realpath?.(path) ?? path), root);
    case "stable":
      return stableAnswer(path);
  }
}

/**
 * A virtual sibling file assigns the exported checks to Record<string, CheckFn> and the reference
 * solve to ReferenceSolveFn. Typechecking therefore compares their signatures with the public
 * contract. The old aggregate evaluator needed this after shiftroster -004 returned custom
 * `{ check, detail }` issues without severity or checkId, preventing reject attribution. The
 * current contract returns Booleans and leaves aggregation to the host. The virtual file stays
 * in memory. Agent tools have no equivalent assignment here because AgentTool<never>[] variance
 * would reject valid toolsets; ordinary argument-count and excess-property checks still apply,
 * and runtime contract checks inspect the generated tools when they load.
 */
function conformanceProbe(slugDir: string) {
  return {
    path: join(slugDir, "correctness-model", "__conformance_probe__.ts").replace(/\\/g, "/"),
    text: `import type { CheckFn, ReferenceSolveFn } from "@ana/correctness-model-bundle";
import { checks } from "./evaluator.ts";
import { solve } from "./reference/index.ts";
const check: Record<string, CheckFn> = checks;
const solveCheck: ReferenceSolveFn = solve;
void check;
void solveCheck;
`,
  };
}

export function typecheckGeneratedModule(
  slugDir: string,
  bundle: "agent" | "correctness-model",
): ContractFinding[] {
  const probeHost = ts.createCompilerHost(PROBE_COMPILER_OPTIONS);
  const root = `${slash(slugDir)}/`;
  const cached = VERDICTS_BY_BUNDLE.get(bundle)?.find((verdict) =>
    verdict.probes.every((probe) => currentAnswer(probeHost, root, probe) === probe.answer),
  );
  if (cached !== undefined) return [...cached.findings];
  const probes = new Map<string, Probe>();
  const findings = typecheck(slugDir, bundle, createProbeCompilerHost(slugDir, probes));
  const verdicts = VERDICTS_BY_BUNDLE.get(bundle) ?? [];
  verdicts.unshift({ probes: [...probes.values()], findings });
  if (verdicts.length > CACHED_VERDICTS) verdicts.pop();
  VERDICTS_BY_BUNDLE.set(bundle, verdicts);
  return [...findings];
}

function typecheck(
  slugDir: string,
  bundle: "agent" | "correctness-model",
  host: ts.CompilerHost,
): ContractFinding[] {
  const rel = bundle === "agent" ? GENERATED_TOOLS_FILE : EVALUATOR_FILE;
  const file = join(slugDir, ...rel.split("/")).replace(/\\/g, "/");
  const virtual = bundle === "correctness-model" ? conformanceProbe(slugDir) : null;
  if (virtual !== null) {
    const base = {
      getSourceFile: host.getSourceFile.bind(host),
      fileExists: host.fileExists.bind(host),
      readFile: host.readFile.bind(host),
    };
    const isVirtual = (name: string) => name.replace(/\\/g, "/") === virtual.path;
    host.getSourceFile = (name, lang, ...rest) =>
      isVirtual(name)
        ? ts.createSourceFile(name, virtual.text, lang)
        : base.getSourceFile(name, lang, ...rest);
    host.fileExists = (name) => isVirtual(name) || base.fileExists(name);
    host.readFile = (name) => (isVirtual(name) ? virtual.text : base.readFile(name));
  }
  const roots = virtual === null ? [file] : [file, virtual.path];
  const program = ts.createProgram(roots, PROBE_COMPILER_OPTIONS, host);
  if (!roots.every((root) => program.getSourceFile(root) !== undefined)) {
    return controllerValidatedFindings([
      {
        code: "generated-module-types",
        path: rel,
        detail: `${rel}: compiler did not load the generated module root`,
      },
    ]);
  }
  // API mistakes in an imported helper are package defects too. The virtual entry reaches both
  // evaluation and reference closures; surrounding dependency diagnostics stay gate-owned.
  const generatedRoot = `${join(slugDir, bundle).replace(/\\/g, "/")}/`;
  // Ask for the diagnostics this gate consumes. Checking every controller/dependency body and
  // discarding its diagnostics afterwards spent ~2 seconds per warm starter probe. Imported
  // types still resolve through the complete program; every generated helper remains checked.
  const diags = ts.sortAndDeduplicateDiagnostics(
    program
      .getSourceFiles()
      .flatMap((source) =>
        source.fileName.replace(/\\/g, "/").startsWith(generatedRoot)
          ? [...program.getSyntacticDiagnostics(source), ...program.getSemanticDiagnostics(source)]
          : [],
      ),
  );
  // This is controller-run type analysis of the model's source, so public feedback keeps its
  // detail. In live-run-01 iteration 1, two of three paid fingerprint attempts lost these
  // diagnostics behind the detail-free generated-execution-unclassified label.
  return controllerValidatedFindings(
    diags.slice(0, 10).map((d) => {
      const message = ts.flattenDiagnosticMessageText(d.messageText, " ");
      const inVirtual =
        virtual !== null && d.file !== undefined && d.file.fileName.replace(/\\/g, "/") === virtual.path;
      const diagnosticPath =
        !inVirtual && d.file ? relative(slugDir, d.file.fileName).replace(/\\/g, "/") : rel;
      let at = diagnosticPath;
      if (!inVirtual && d.file && d.start !== undefined) {
        const { line, character } = d.file.getLineAndCharacterOfPosition(d.start);
        at = `${diagnosticPath}:${line + 1}:${character + 1}`;
      }
      return {
        code: "generated-module-types",
        path: diagnosticPath,
        detail: inVirtual
          ? `the evaluation package exports must conform to Record<string, CheckFn> and ReferenceSolveFn — TS${d.code}: ${message}`
          : `${at} TS${d.code}: ${message}`,
      };
    }),
  );
}
